"""initial catalog schema

Revision ID: 8278fbd6b06e
Revises: 
Create Date: 2026-09-09 15:58:17.107155
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8278fbd6b06e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=250), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('score_hint', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_snapshots_captured_at'), 'repository_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_repo_full_name'), 'repository_snapshots', ['repo_full_name'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=500), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('repo_full_name', sa.String(length=250), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_default_branch', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('compatibility', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('allowed_tools_json', sa.JSON(), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('security_json', sa.JSON(), nullable=False),
    sa.Column('score_json', sa.JSON(), nullable=False),
    sa.Column('resources_json', sa.JSON(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('discovery_source', sa.String(length=100), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('maintenance_score', sa.Integer(), nullable=False),
    sa.Column('adoption_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_key'), 'skills', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_skills_content_fingerprint'), 'skills', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_skills_discovery_source'), 'skills', ['discovery_source'], unique=False)
    op.create_index(op.f('ix_skills_first_seen_at'), 'skills', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_skills_indexed_at'), 'skills', ['indexed_at'], unique=False)
    op.create_index(op.f('ix_skills_is_active'), 'skills', ['is_active'], unique=False)
    op.create_index(op.f('ix_skills_last_seen_at'), 'skills', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_skills_overall_score'), 'skills', ['overall_score'], unique=False)
    op.create_index(op.f('ix_skills_pushed_at'), 'skills', ['pushed_at'], unique=False)
    op.create_index(op.f('ix_skills_repo_full_name'), 'skills', ['repo_full_name'], unique=False)
    op.create_index(op.f('ix_skills_stars'), 'skills', ['stars'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_stars'), table_name='skills')
    op.drop_index(op.f('ix_skills_repo_full_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_pushed_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_overall_score'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_last_seen_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_active'), table_name='skills')
    op.drop_index(op.f('ix_skills_indexed_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_first_seen_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_discovery_source'), table_name='skills')
    op.drop_index(op.f('ix_skills_content_fingerprint'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_key'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_repository_snapshots_repo_full_name'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_captured_at'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    # ### end Alembic commands ###
