from __future__ import annotations

import json
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from .catalog import catalog_stats, export_catalog, records_as_dicts, repository_rollups
from .materialized import materialize_records as materialize_published_catalog

README_START = "<!-- AWESOME_INDEX_START -->"
README_END = "<!-- AWESOME_INDEX_END -->"


def _clean_cell(value: Any, limit: int = 120) -> str:
    text = " ".join(str(value or "").split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _manifest(row: dict[str, Any]) -> str:
    evidence = row.get("evidence") or {}
    manifest = evidence.get("manifest")
    if isinstance(manifest, str) and manifest:
        return manifest
    branch = row.get("repo_default_branch") or "main"
    path = str(row.get("path") or ".")
    suffix = "SKILL.md" if path == "." else f"{path}/SKILL.md"
    return f"{row['repo_url']}/blob/{branch}/{suffix}"


def _clients(row: dict[str, Any]) -> list[str]:
    evidence = row.get("evidence") or {}
    clients = evidence.get("client_compatibility_evidence") or {}
    if not isinstance(clients, dict):
        return []
    return sorted(str(name) for name in clients)


def _anchor(value: str) -> str:
    return "".join(char for char in value.lower().replace(" ", "-") if char.isalnum() or char == "-")


def render_readme_block(
    rows: list[dict[str, Any]],
    stats: dict[str, Any],
    generated_at: datetime,
    *,
    limit: int = 12,
) -> str:
    top = [row for row in rows if (row.get("spec") or {}).get("valid")][:limit]
    lines = [
        f"Last refreshed: **{generated_at.astimezone(UTC):%Y-%m-%d %H:%M UTC}**",
        "",
        (
            f"**{stats.get('skills', 0)} verified skills** across "
            f"**{stats.get('repositories', 0)} repositories** · "
            f"{stats.get('security_85_plus', 0)} with security score 85+ · "
            f"{stats.get('score_80_plus', 0)} with overall score 80+"
        ),
        "",
        "[Browse the full Awesome catalog](./AWESOME.md) · "
        "[Open the GitHub Awesome path](./awesome/) · "
        "[Download JSON](./data/catalog.json) · [Repositories JSON](./data/repositories.json)",
        "",
        "### Top verified skills",
        "",
        "| Skill | Repository | Score | Security | Stars | Category |",
        "|---|---|---:|---:|---:|---|",
    ]
    if not top:
        lines.append("| _No verified skills indexed yet_ |  |  |  |  |  |")
    for row in top:
        score = row.get("score") or {}
        categories = (row.get("evidence") or {}).get("categories") or []
        lines.append(
            "| "
            f"[{_clean_cell(row.get('name'), 64)}]({_manifest(row)}) | "
            f"[{_clean_cell(row.get('repo_full_name'), 80)}]({row.get('repo_url')}) | "
            f"{int(score.get('overall') or 0)} | "
            f"{int(score.get('security') or 0)} | "
            f"{int(row.get('stars') or 0)} | "
            f"{_clean_cell(', '.join(categories[:2]) or 'uncategorized', 50)} |"
        )
    return "\n".join(lines)


def render_awesome_markdown(
    rows: list[dict[str, Any]],
    repos: list[dict[str, Any]],
    stats: dict[str, Any],
    generated_at: datetime,
    *,
    data_prefix: str = "./data",
) -> str:
    valid_rows = [row for row in rows if (row.get("spec") or {}).get("valid")]
    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in valid_rows:
        categories = (row.get("evidence") or {}).get("categories") or ["uncategorized"]
        for category in categories:
            by_category[str(category)].append(row)

    top = sorted(
        valid_rows,
        key=lambda row: (
            -int((row.get("score") or {}).get("overall") or 0),
            -int(row.get("stars") or 0),
            str(row.get("name") or ""),
        ),
    )[:25]

    lines = [
        "# Awesome Agent Skills & Repositories",
        "",
        "Evidence-backed directory generated by Agent Skill Observatory. A repository appears here only after a real `SKILL.md` has been fetched and parsed.",
        "",
        f"> Last refreshed: {generated_at.astimezone(UTC):%Y-%m-%d %H:%M UTC}",
        "> The crawler checks GitHub every 15 minutes. Scores are review signals, not a guarantee that third-party code is safe to execute.",
        "",
        "## Snapshot",
        "",
        f"- **{stats.get('skills', 0)}** indexed skills",
        f"- **{stats.get('repositories', 0)}** repositories",
        f"- **{stats.get('spec_valid', 0)}** spec-valid manifests",
        f"- **{stats.get('security_85_plus', 0)}** skills with security score 85+",
        f"- **{stats.get('score_80_plus', 0)}** skills with overall score 80+",
        "",
        "## Browse by category",
        "",
    ]
    if not by_category:
        lines.append("_Categories will appear after the first successful catalog refresh._")
    else:
        for category in sorted(by_category):
            lines.append(f"- [{category}](#{_anchor(category)}) · {len(by_category[category])} skills")

    lines += [
        "",
        "## Top verified skills",
        "",
        "| Skill | Repository | Score | Security | Stars | Clients | Category |",
        "|---|---|---:|---:|---:|---|---|",
    ]
    if not top:
        lines.append("| _No verified skills indexed yet_ |  |  |  |  |  |  |")
    for row in top:
        score = row.get("score") or {}
        categories = (row.get("evidence") or {}).get("categories") or []
        clients = _clients(row)
        lines.append(
            "| "
            f"[{_clean_cell(row.get('name'), 64)}]({_manifest(row)}) | "
            f"[{_clean_cell(row.get('repo_full_name'), 80)}]({row.get('repo_url')}) | "
            f"{int(score.get('overall') or 0)} | {int(score.get('security') or 0)} | "
            f"{int(row.get('stars') or 0)} | "
            f"{_clean_cell(', '.join(clients) or 'open standard', 70)} | "
            f"{_clean_cell(', '.join(categories[:2]) or 'uncategorized', 50)} |"
        )

    lines += [
        "",
        "## Repository directory",
        "",
        "| Repository | Skills | Spec valid | Security 85+ | Best score | Stars | Categories |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    if not repos:
        lines.append("| _No repositories indexed yet_ | 0 | 0 | 0 | 0 | 0 |  |")
    for repo in repos:
        lines.append(
            "| "
            f"[{_clean_cell(repo['repo_full_name'], 90)}]({repo['repo_url']}) | "
            f"{repo['skills_count']} | {repo['spec_valid_count']} | {repo['security_85_plus_count']} | "
            f"{repo['best_score']} | {repo['stars']} | "
            f"{_clean_cell(', '.join(repo['categories'][:4]) or 'uncategorized', 80)} |"
        )

    lines += ["", "## Skills by category", ""]
    if not by_category:
        lines.extend(["_No verified skills indexed yet._", ""])
    for category in sorted(by_category):
        lines += [
            f"### {category}",
            "",
            "| Skill | Repository | Score | Security | Stars | Clients | Description |",
            "|---|---|---:|---:|---:|---|---|",
        ]
        category_rows = sorted(
            by_category[category],
            key=lambda row: (
                -int((row.get("score") or {}).get("overall") or 0),
                -int(row.get("stars") or 0),
                str(row.get("name") or ""),
            ),
        )
        for row in category_rows:
            score = row.get("score") or {}
            clients = _clients(row)
            lines.append(
                "| "
                f"[{_clean_cell(row.get('name'), 64)}]({_manifest(row)}) | "
                f"[{_clean_cell(row.get('repo_full_name'), 80)}]({row.get('repo_url')}) | "
                f"{int(score.get('overall') or 0)} | {int(score.get('security') or 0)} | "
                f"{int(row.get('stars') or 0)} | "
                f"{_clean_cell(', '.join(clients) or 'open standard', 70)} | "
                f"{_clean_cell(row.get('description'), 110)} |"
            )
        lines.append("")

    lines += [
        "## Machine-readable data",
        "",
        f"- [`data/catalog.json`]({data_prefix}/catalog.json): skill-level records, provenance, scores and evidence",
        f"- [`data/repositories.json`]({data_prefix}/repositories.json): repository rollups with contained skills",
        f"- [`data/catalog.csv`]({data_prefix}/catalog.csv): analysis-friendly flat export",
        f"- [`data/stats.json`]({data_prefix}/stats.json): headline counts",
        f"- [`data/refresh.json`]({data_prefix}/refresh.json): publication timestamp",
        "",
        "## How entries get here",
        "",
        "1. Broad GitHub discovery finds candidate repositories.",
        "2. The crawler fetches the repository tree and requires a real `SKILL.md`.",
        "3. The manifest is parsed and checked against the open Agent Skills format.",
        "4. Supporting text files are inspected statically without executing third-party code.",
        "5. Category, client evidence, maintenance, adoption and score signals are recorded.",
        "6. This directory, the root README summary and machine-readable exports are regenerated.",
        "",
        "Generated automatically. Do not edit this file by hand.",
    ]
    return "\n".join(lines).rstrip() + "\n"


def rewrite_readme(readme_path: Path, block: str) -> None:
    text = readme_path.read_text(encoding="utf-8")
    section = f"{README_START}\n{block.rstrip()}\n{README_END}"
    if README_START in text and README_END in text:
        before, rest = text.split(README_START, 1)
        _, after = rest.split(README_END, 1)
        text = before.rstrip() + "\n\n" + section + after
    else:
        text = text.rstrip() + "\n\n## Live Awesome Index\n\n" + section + "\n"
    readme_path.write_text(text, encoding="utf-8")


def publish_catalog(
    session: Session,
    *,
    data_dir: Path = Path("data"),
    readme_path: Path = Path("README.md"),
    awesome_path: Path = Path("AWESOME.md"),
    awesome_directory_path: Path | None = None,
    generated_at: datetime | None = None,
) -> dict[str, Any]:
    generated = generated_at or datetime.now(UTC)
    data_dir.mkdir(parents=True, exist_ok=True)
    export_catalog(session, data_dir / "catalog.json", format="json")
    export_catalog(session, data_dir / "catalog.csv", format="csv")
    rows = records_as_dicts(session)
    stats = catalog_stats(session)
    repos = repository_rollups(session)
    (data_dir / "stats.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    (data_dir / "repositories.json").write_text(
        json.dumps(repos, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (data_dir / "refresh.json").write_text(
        json.dumps({"generated_at": generated.isoformat()}, indent=2) + "\n", encoding="utf-8"
    )
    awesome_markdown = render_awesome_markdown(rows, repos, stats, generated, data_prefix="./data")
    awesome_path.parent.mkdir(parents=True, exist_ok=True)
    awesome_path.write_text(awesome_markdown, encoding="utf-8")
    if awesome_directory_path is not None:
        awesome_directory_path.parent.mkdir(parents=True, exist_ok=True)
        awesome_directory_path.write_text(
            render_awesome_markdown(rows, repos, stats, generated, data_prefix="../data"),
            encoding="utf-8",
        )
    rewrite_readme(readme_path, render_readme_block(rows, stats, generated))
    return stats
